# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
d1 = Doctor.create({ name: 'Sally', email: 'sally@example.com', password: 'aaaaaaaa', password_confirmation: 'aaaaaaaa', DOB: Date.new(1980, 9, 17), graduated: 2001, city: 'Barcelona', resume:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris posuere ante eget lacus ultricies, et laoreet nunc scelerisque. Curabitur vulputate suscipit pellentesque. Nunc molestie purus nisl, eu porttitor lorem pretium a. Duis sagittis, dui id lobortis gravida, quam diam placerat magna, lobortis tempor odio erat vitae felis. Nulla venenatis est lorem. Suspendisse dapibus ante odio, vel consectetur diam rhoncus varius. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vitae porta metus. Mauris porta at massa quis iaculis. Aenean et blandit tellus. Donec pellentesque ipsum metus.' })
d2 = Doctor.create({ name: 'Sue', email: 'sue@example.com', password: 'aaaaaaaa', password_confirmation: 'aaaaaaaa', DOB: Date.new(1981, 10, 17), graduated: 2004, city: 'London', resume:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris posuere ante eget lacus ultricies, et laoreet nunc scelerisque. Curabitur vulputate suscipit pellentesque. Nunc molestie purus nisl, eu porttitor lorem pretium a. Duis sagittis, dui id lobortis gravida, quam diam placerat magna, lobortis tempor odio erat vitae felis. Nulla venenatis est lorem. Suspendisse dapibus ante odio, vel consectetur diam rhoncus varius. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vitae porta metus. Mauris porta at massa quis iaculis. Aenean et blandit tellus. Donec pellentesque ipsum metus.' })
d3 = Doctor.create({ name: 'Kev', email: 'kev@example.com', password: 'aaaaaaaa', password_confirmation: 'aaaaaaaa', DOB: Date.new(1979, 9, 23), graduated: 1999, city: 'Paris', resume:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris posuere ante eget lacus ultricies, et laoreet nunc scelerisque. Curabitur vulputate suscipit pellentesque. Nunc molestie purus nisl, eu porttitor lorem pretium a. Duis sagittis, dui id lobortis gravida, quam diam placerat magna, lobortis tempor odio erat vitae felis. Nulla venenatis est lorem. Suspendisse dapibus ante odio, vel consectetur diam rhoncus varius. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vitae porta metus. Mauris porta at massa quis iaculis. Aenean et blandit tellus. Donec pellentesque ipsum metus.' })
d4 = Doctor.create({ name: 'Jack', email: 'jack@example.com', password: 'aaaaaaaa', password_confirmation: 'aaaaaaaa', DOB: Date.new(1983, 9, 17), graduated: 2005, city: 'Hanoi', resume:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris posuere ante eget lacus ultricies, et laoreet nunc scelerisque. Curabitur vulputate suscipit pellentesque. Nunc molestie purus nisl, eu porttitor lorem pretium a. Duis sagittis, dui id lobortis gravida, quam diam placerat magna, lobortis tempor odio erat vitae felis. Nulla venenatis est lorem. Suspendisse dapibus ante odio, vel consectetur diam rhoncus varius. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vitae porta metus. Mauris porta at massa quis iaculis. Aenean et blandit tellus. Donec pellentesque ipsum metus.' })

p1 = Patient.create({ name: 'John', surname: 'Wilkins', email: 'john@example.com', password: 'aaaaaaaa', password_confirmation: 'aaaaaaaa', DOB: Date.new(1965, 9, 11), city: 'Montpellier', medical_history:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris posuere ante eget lacus ultricies, et laoreet nunc scelerisque. Curabitur vulputate suscipit pellentesque. Nunc molestie purus nisl, eu porttitor lorem pretium a. Duis sagittis, dui id lobortis gravida, quam diam placerat magna, lobortis tempor odio erat vitae felis. Nulla venenatis est lorem. Suspendisse dapibus ante odio, vel consectetur diam rhoncus varius. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vitae porta metus. Mauris porta at massa quis iaculis. Aenean et blandit tellus. Donec pellentesque ipsum metus.' })
p2 = Patient.create({ name: 'Alexa', surname: 'McEnroe', email: 'alexa@example.com', password: 'aaaaaaaa', password_confirmation: 'aaaaaaaa', DOB: Date.new(1995, 10, 19), city: 'New York', medical_history:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris posuere ante eget lacus ultricies, et laoreet nunc scelerisque. Curabitur vulputate suscipit pellentesque. Nunc molestie purus nisl, eu porttitor lorem pretium a. Duis sagittis, dui id lobortis gravida, quam diam placerat magna, lobortis tempor odio erat vitae felis. Nulla venenatis est lorem. Suspendisse dapibus ante odio, vel consectetur diam rhoncus varius. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vitae porta metus. Mauris porta at massa quis iaculis. Aenean et blandit tellus. Donec pellentesque ipsum metus.' })
p3 = Patient.create({ name: 'Woody', surname: 'Allen', email: 'woody@example.com', password: 'aaaaaaaa', password_confirmation: 'aaaaaaaa', DOB: Date.new(1988, 9, 23), city: 'Berlin', medical_history:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris posuere ante eget lacus ultricies, et laoreet nunc scelerisque. Curabitur vulputate suscipit pellentesque. Nunc molestie purus nisl, eu porttitor lorem pretium a. Duis sagittis, dui id lobortis gravida, quam diam placerat magna, lobortis tempor odio erat vitae felis. Nulla venenatis est lorem. Suspendisse dapibus ante odio, vel consectetur diam rhoncus varius. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vitae porta metus. Mauris porta at massa quis iaculis. Aenean et blandit tellus. Donec pellentesque ipsum metus.' })
p4 = Patient.create({ name: 'Kevin', surname: 'Durant', email: 'kevin@example.com', password: 'aaaaaaaa', password_confirmation: 'aaaaaaaa', DOB: Date.new(1991, 9, 17), city: 'HCMC', medical_history:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris posuere ante eget lacus ultricies, et laoreet nunc scelerisque. Curabitur vulputate suscipit pellentesque. Nunc molestie purus nisl, eu porttitor lorem pretium a. Duis sagittis, dui id lobortis gravida, quam diam placerat magna, lobortis tempor odio erat vitae felis. Nulla venenatis est lorem. Suspendisse dapibus ante odio, vel consectetur diam rhoncus varius. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam vitae porta metus. Mauris porta at massa quis iaculis. Aenean et blandit tellus. Donec pellentesque ipsum metus.' })